//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "historicals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub fiscal_year: i32,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub sales: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub eps: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub price_high: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub price_low: Decimal,
    pub currency: String,
    pub is_split_adjusted: Option<bool>,
    pub adjustment_factor: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
