//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "locked_analyses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker_id: i32,
    pub snapshot_data: Json,
    pub analyst_note: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tickers::Entity",
        from = "Column::TickerId",
        to = "super::tickers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tickers,
}

impl Related<super::tickers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tickers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
