//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::exchange_rates::Entity as ExchangeRates;
pub use super::historicals::Entity as Historicals;
pub use super::tickers::Entity as Tickers;
pub use super::users::Entity as Users;
