//! QA gap-coverage suite for `core::golden` (Story 1.9) — generated by the QA automation
//! workflow over the public consumer surface `GoldenStudy` (serde) → `check` / `check_all`
//! → `GoldenReport`, exactly as the Story-2.13 "verify engine" screen will call it.
//!
//! Complements `golden_gate.rs` (the CI gate + AC-6 negative controls) and the in-module
//! unit tests with the behaviours neither pins: `check_all` over the real bundle with a
//! mixed pass/fail outcome, deviation ACCUMULATION across sections (the report is a full
//! list, not a first-failure), ordered-list reporting for flags and findings, the U/D
//! state-exact/value-tolerant split, `zones` null ⇔ computed mismatches, the optional
//! per-year-table semantics (omitted / tampered / row-count), the symmetric tolerance on a
//! NEGATIVE expected value, and the `GoldenDeviation` Display string 2.13 renders. Same
//! tamper discipline as the gate: variants exist only in memory, never as fixture files.

use std::fs;
use std::path::{Path, PathBuf};
use steadyinvest_core::golden::{check, check_all, GoldenStudy};

/// The trusted tamper bases: real on-disk fixtures (never modified on disk).
const G01: &str = include_str!("golden/g01-worked-example.json");
const G09: &str = include_str!("golden/g09-unknown-rich-degenerate.json");

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

/// Apply a targeted textual tamper, asserting it actually changed something.
fn tampered(base: &str, from: &str, to: &str) -> String {
    let out = base.replace(from, to);
    assert_ne!(out, base, "tamper {from:?} -> {to:?} did not apply");
    out
}

fn check_str(json: &str) -> steadyinvest_core::golden::GoldenReport {
    let study: GoldenStudy = serde_json::from_str(json).expect("tampered study still parses");
    check(&study)
}

/// Parse, structurally edit (for tampers a textual replace cannot express, e.g. removing a
/// key), and re-check.
fn check_value(
    edit: impl FnOnce(&mut serde_json::Value),
) -> steadyinvest_core::golden::GoldenReport {
    let mut value: serde_json::Value = serde_json::from_str(G01).expect("g01 is valid JSON");
    edit(&mut value);
    let study: GoldenStudy =
        serde_json::from_value(value).expect("structurally edited study still parses");
    check(&study)
}

/// The literal Story-2.13 consumption path: load every bundled fixture, `check_all`, and
/// read the reports — order and ids must follow the input bundle; one stale study appended
/// to the bundle fails alone without affecting the others.
#[test]
fn check_all_over_the_real_bundle_reports_in_input_order_and_isolates_failures() {
    let mut names: Vec<String> = fs::read_dir(fixtures_dir())
        .expect("fixtures directory exists")
        .map(|e| e.expect("readable entry").path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "json"))
        .map(|p| p.to_string_lossy().into_owned())
        .collect();
    names.sort();
    let mut studies: Vec<GoldenStudy> = names
        .iter()
        .map(|p| {
            let text = fs::read_to_string(p).expect("readable fixture");
            serde_json::from_str(&text).unwrap_or_else(|e| panic!("{p} failed to parse: {e}"))
        })
        .collect();
    assert!(studies.len() >= 10, "the AC-4 bundle is the test subject");

    let expected_ids: Vec<String> = studies.iter().map(|s| s.meta.id.clone()).collect();
    let reports = check_all(&studies);
    assert_eq!(reports.len(), studies.len());
    let report_ids: Vec<String> = reports.iter().map(|r| r.id.clone()).collect();
    assert_eq!(report_ids, expected_ids, "reports follow the input order");
    for report in &reports {
        assert!(
            report.passed,
            "{} deviates: {:?}",
            report.id, report.deviations
        );
    }

    // Mixed bundle: a stale-method study appended at the end fails alone.
    let stale = tampered(
        G01,
        "\"method_version\": \"ssg-1.0.0\"",
        "\"method_version\": \"ssg-0.9.9\"",
    );
    studies.push(serde_json::from_str(&stale).expect("stale variant parses"));
    let reports = check_all(&studies);
    let (last, rest) = reports.split_last().expect("non-empty");
    assert!(
        rest.iter().all(|r| r.passed),
        "other studies are unaffected"
    );
    assert!(!last.passed);
    assert_eq!(
        last.id, "g01-worked-example",
        "a failing report still carries its id"
    );
    assert_eq!(last.deviations.len(), 1);
    assert_eq!(last.deviations[0].path, "meta.method_version");
}

/// The report is a full deviation LIST: categorical tampers across five sections are all
/// reported in the documented section pass order, none short-circuits the others, and a
/// categorical deviation never carries a relative error.
#[test]
fn categorical_deviations_accumulate_across_sections_in_pass_order() {
    let mut json = tampered(G01, "\"ptp_trend\": \"down\"", "\"ptp_trend\": \"up\"");
    // Replaces BOTH occurrences: risk_reward and verdict_facts.
    json = tampered(
        &json,
        "\"present_price_zone\": \"buy\"",
        "\"present_price_zone\": \"sell\"",
    );
    json = tampered(
        &json,
        "\"low_confidence\": false",
        "\"low_confidence\": true",
    );
    json = tampered(
        &json,
        "\"ud_at_or_above_target\": \"met\"",
        "\"ud_at_or_above_target\": \"unmet\"",
    );
    json = tampered(
        &json,
        "\"quality_value_candidate\": true",
        "\"quality_value_candidate\": false",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    let paths: Vec<&str> = report.deviations.iter().map(|d| d.path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "management.ptp_trend",
            "risk_reward.present_price_zone",
            "low_confidence",
            "verdict_facts.present_price_zone",
            "verdict_facts.ud_at_or_above_target",
            "verdict_facts.quality_value_candidate",
        ],
        "all six deviations reported, in the section pass order"
    );
    for deviation in &report.deviations {
        assert_eq!(
            deviation.relative_error, None,
            "categorical comparisons carry no relative error: {deviation}"
        );
    }
}

/// The quality-flag list compares as ONE ordered-list deviation carrying both full lists —
/// the rendering 2.13 will show for a flag mismatch.
#[test]
fn tampered_quality_flag_list_is_one_deviation_carrying_both_lists() {
    let json = tampered(
        G01,
        "\"quality_flags\": [\"ptp_trend_declining\"]",
        "\"quality_flags\": []",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "quality_flags");
    assert_eq!(deviation.expected, "[]");
    assert_eq!(deviation.actual, "[ptp_trend_declining]");
}

/// Calc-time AND normalize-side finding mismatches are both reported, each as an
/// ordered-list deviation with the documented finding rendering (study-level vs per-year).
#[test]
fn tampered_findings_and_normalize_findings_are_both_reported() {
    let mut json = tampered(
        G01,
        "\"findings\": []",
        "\"findings\": [{ \"key\": \"split_series_break\", \"year\": null, \"context\": \"eps\" }]",
    );
    json = tampered(
        &json,
        "\"normalize_findings\": []",
        "\"normalize_findings\": [{ \"key\": \"split_series_break\", \"year\": 2022, \"context\": \"eps\" }]",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 2);
    let normalize = report
        .deviations
        .iter()
        .find(|d| d.path == "normalize_findings")
        .expect("normalize_findings deviation");
    assert_eq!(
        normalize.expected,
        "[split_series_break year 2022 context eps]"
    );
    assert_eq!(normalize.actual, "[]");
    let calc = report
        .deviations
        .iter()
        .find(|d| d.path == "findings")
        .expect("findings deviation");
    assert_eq!(
        calc.expected,
        "[split_series_break study-level context eps]"
    );
    assert_eq!(calc.actual, "[]");
}

/// U/D: the three-way STATE is exact (ratio vs unknown deviates), while a Ratio's value is
/// an ordinary tolerance-compared numeric.
#[test]
fn upside_downside_state_is_exact_while_its_ratio_value_is_tolerance_compared() {
    // State mismatch: expected unknown, actual a measured ratio -> exact deviation.
    let json = tampered(
        G01,
        "\"upside_downside\": { \"ratio\": \"4.9610666667\" }",
        "\"upside_downside\": \"unknown\"",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "risk_reward.upside_downside");
    assert_eq!(deviation.expected, "unknown");
    assert!(
        deviation.actual.starts_with("ratio 4.9610666"),
        "actual renders the measured state: {}",
        deviation.actual
    );

    // Value within ±0.5% of the expected ratio: passes (tolerance, not exactness).
    let json = tampered(
        G01,
        "{ \"ratio\": \"4.9610666667\" }",
        "{ \"ratio\": \"4.97\" }",
    );
    let report = check_str(&json);
    assert!(
        report.passed,
        "a ratio inside the tolerance passes: {:?}",
        report.deviations
    );
}

/// Expected `zones: null` while the engine computes bounds is a single structural deviation
/// (the null ⇔ present rule for the whole bounds block, not four numeric misses).
#[test]
fn expected_null_zones_against_computed_bounds_is_a_structural_deviation() {
    let report = check_value(|v| v["expected"]["risk_reward"]["zones"] = serde_json::Value::Null);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "risk_reward.zones");
    assert_eq!(deviation.expected, "null");
    assert!(
        deviation.actual.starts_with('[') && deviation.actual.contains("23.32992"),
        "actual renders the computed bounds: {}",
        deviation.actual
    );
    assert_eq!(deviation.relative_error, None);
}

/// The optional blocks (both per-year tables and `normalize_findings`) really are
/// omitted-=-not-asserted: removing all three from the fullest fixture still passes.
#[test]
fn omitted_optional_blocks_are_not_asserted() {
    let report = check_value(|v| {
        let expected = v["expected"].as_object_mut().expect("expected block");
        expected.remove("normalize_findings");
        expected["management"]
            .as_object_mut()
            .expect("management block")
            .remove("per_year");
        expected["valuation"]
            .as_object_mut()
            .expect("valuation block")
            .remove("per_year");
    });
    assert!(
        report.passed,
        "omitted optional blocks assert nothing: {:?}",
        report.deviations
    );
}

/// A PRESENT per-year table is asserted: a tampered row value deviates under its
/// year-indexed path, and a wrong row count is one structural "rows" deviation.
#[test]
fn present_per_year_tables_are_asserted_by_row_and_by_count() {
    let json = tampered(
        G01,
        "{ \"year\": 2023, \"ptp_pct\": \"10\", \"roe_pct\": \"20\" }",
        "{ \"year\": 2023, \"ptp_pct\": \"10.2\", \"roe_pct\": \"20\" }",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "management.per_year[2023].ptp_pct");
    assert_eq!(deviation.expected, "10.2");
    assert!(deviation.relative_error.is_some());

    let report = check_value(|v| {
        v["expected"]["management"]["per_year"]
            .as_array_mut()
            .expect("per-year rows")
            .pop();
    });
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "management.per_year");
    assert_eq!(deviation.expected, "4 rows");
    assert_eq!(deviation.actual, "5 rows");
}

/// The ±0.5% tolerance is symmetric around a NEGATIVE expected value too (|expected| in the
/// spec-§7 formula): g09's TTM EPS is −0.40 by hand computation.
#[test]
fn tolerance_is_relative_to_the_magnitude_of_a_negative_expected_value() {
    // Expected −0.4018, actual −0.40: diff 0.0018 ≤ 0.005 × 0.4018 = 0.002009 -> passes.
    let inside = tampered(G09, "\"ttm_eps\": \"-0.40\"", "\"ttm_eps\": \"-0.4018\"");
    let report = check_str(&inside);
    assert!(
        report.passed,
        "a negative value inside the tolerance passes: {:?}",
        report.deviations
    );

    // Expected −0.4021, actual −0.40: diff 0.0021 > 0.005 × 0.4021 = 0.0020105 -> deviates.
    let beyond = tampered(G09, "\"ttm_eps\": \"-0.40\"", "\"ttm_eps\": \"-0.4021\"");
    let report = check_str(&beyond);
    assert!(!report.passed);
    assert_eq!(report.deviations.len(), 1);
    let deviation = &report.deviations[0];
    assert_eq!(deviation.path, "valuation.ttm_eps");
    assert!(deviation.relative_error.is_some());
}

/// The `GoldenDeviation` Display string is the line Story 2.13 renders: numeric deviations
/// carry the relative-error suffix, categorical ones end at the actual value.
#[test]
fn deviation_display_renders_path_values_and_optional_relative_error() {
    let json = tampered(
        G01,
        "\"sales_cagr_pct\": \"10\"",
        "\"sales_cagr_pct\": \"20\"",
    );
    let report = check_str(&json);
    assert!(!report.passed);
    let numeric = report
        .deviations
        .iter()
        .find(|d| d.path == "growth.sales_cagr_pct")
        .expect("CAGR deviation");
    let rendered = numeric.to_string();
    assert!(
        rendered.starts_with("growth.sales_cagr_pct: expected 20, actual 10"),
        "unexpected rendering: {rendered}"
    );
    assert!(
        rendered.contains("(relative error 0.5"),
        "the numeric suffix renders the relative error: {rendered}"
    );

    let json = tampered(
        G01,
        "\"present_price_zone\": \"buy\"",
        "\"present_price_zone\": \"sell\"",
    );
    let report = check_str(&json);
    let categorical = report
        .deviations
        .iter()
        .find(|d| d.path == "risk_reward.present_price_zone")
        .expect("zone deviation");
    assert_eq!(
        categorical.to_string(),
        "risk_reward.present_price_zone: expected sell, actual buy",
        "categorical rendering carries no relative-error suffix"
    );
}
