//! QA gap-coverage suite for `core::ssg` (Story 1.8) — generated by the QA automation
//! workflow over the public end-to-end pipeline `normalize → compute`.
//!
//! Complements `ssg_engine.rs` (worked example, §9 table, boundary comparators) with the
//! paths the dev suite leaves untested at the integration level: the forecast-low options
//! (b)/(c), the positive firing of `eps_lags_sales` / `roe_low` / `roe_trend_declining` /
//! `ud_below_target`, Neutral/Sell zone classification with measured-miss verdict facts,
//! `out_of_bounds_ratio` driven through the engine, the direct-only low-EPS rule's
//! degradation cascade, and the Up trend. Same fixture discipline as `ssg_engine.rs`:
//! exact-by-construction values, hand-computed expectations in the assert messages.

use rust_decimal::Decimal;
use steadyinvest_core::normalize::{
    normalize, CanonicalFinancials, PlausibilityKey, RawAmount, RawYear,
};
use steadyinvest_core::ssg::{
    compute, CalcFinding, CriterionFact, ForecastLowOption, JudgmentInputs, QualityFlagKey,
    QuarterlyObservations, Trend, UpsideDownside, Zone,
};

fn d(s: &str) -> Decimal {
    s.parse()
        .unwrap_or_else(|_| panic!("bad decimal literal {s:?}"))
}

fn amt(s: &str) -> Option<RawAmount> {
    Some(RawAmount {
        value: d(s),
        currency: "USD".to_string(),
    })
}

/// One fully-populated raw year (all 7 value fields) — same builder as `ssg_engine.rs`.
#[allow(clippy::too_many_arguments)]
fn full_year(
    year: i32,
    sales: &str,
    eps: &str,
    high: &str,
    low: &str,
    dividend: &str,
    ptp: &str,
    book_value: &str,
) -> RawYear {
    let mut y = RawYear::empty(year);
    y.sales = amt(sales);
    y.eps = amt(eps);
    y.high_price = amt(high);
    y.low_price = amt(low);
    y.dividend_per_share = amt(dividend);
    y.pre_tax_profit = amt(ptp);
    y.book_value_per_share = amt(book_value);
    y
}

fn canonical(years: Vec<RawYear>) -> CanonicalFinancials {
    normalize(steadyinvest_core::normalize::RawFinancials {
        native_currency: "USD".to_string(),
        years,
        splits: vec![],
    })
    .expect("structurally valid fixture")
}

/// The `ssg_engine.rs` tutorial company: 5 usable years of exact 1.1-powers, constant
/// high P/E 20 / low P/E 10 / payout 30% / ROE 20%, PTP marching down 12% → 8%.
fn tutorial_financials() -> CanonicalFinancials {
    canonical(vec![
        full_year(
            2021, "1000", "1.00", "20.00", "10.00", "0.30", "120", "5.00",
        ),
        full_year(
            2022, "1100", "1.10", "22.00", "11.00", "0.33", "121", "5.50",
        ),
        full_year(
            2023, "1210", "1.21", "24.20", "12.10", "0.363", "121", "6.05",
        ),
        full_year(
            2024, "1331", "1.331", "26.62", "13.31", "0.3993", "119.79", "6.655",
        ),
        full_year(
            2025, "1464.1", "1.4641", "29.282", "14.641", "0.43923", "117.128", "7.3205",
        ),
    ])
}

/// Tutorial judgment: forecast high = 18 × 2.48832 = 44.78976, option (a) low = 9 × 1.40
/// = 12.6, current price 18.
fn tutorial_judgment() -> JudgmentInputs {
    let mut j = JudgmentInputs::empty();
    j.estimated_high_eps = Some(d("2.48832"));
    j.estimated_low_eps = Some(d("1.40"));
    j.projected_sales_growth_pct = Some(d("10"));
    j.projected_eps_growth_pct = Some(d("10"));
    j.judged_avg_high_pe = Some(d("18"));
    j.judged_avg_low_pe = Some(d("9"));
    j.forecast_low_option = ForecastLowOption::AvgLowPeTimesEps;
    j.current_price = Some(d("18"));
    j.present_full_year_dividend = Some(d("0.45"));
    j
}

fn tutorial_observations() -> QuarterlyObservations {
    let mut o = QuarterlyObservations::empty();
    o.ttm_quarterly_eps = Some([d("0.40"), d("0.40"), d("0.40"), d("0.40")]); // TTM = 1.60
    o.latest_quarter_sales = Some(d("400"));
    o.year_ago_quarter_sales = Some(d("320"));
    o.latest_quarter_eps = Some(d("0.40"));
    o.year_ago_quarter_eps = Some(d("0.32"));
    o
}

// ── Forecast-low options (b) and (c) — never exercised by the dev suite ──

/// Option (b): the forecast low is the §3 average low price of the window —
/// (10 + 11 + 12.1 + 13.31 + 14.641) / 5 = 12.2102 exactly.
#[test]
fn forecast_low_option_b_uses_the_average_low_price() {
    let mut judgment = tutorial_judgment();
    judgment.forecast_low_option = ForecastLowOption::AvgLowPriceLast5y;
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    assert_eq!(
        out.valuation.avg_low_price,
        Some(d("12.2102")),
        "the §3 average low price option (b) divides by"
    );
    assert_eq!(
        out.risk_reward.forecast_low,
        Some(d("12.2102")),
        "option (b) = avg low price verbatim"
    );
    assert_eq!(
        out.risk_reward.present_price_zone,
        Some(Zone::Buy),
        "18 is inside the first third of [12.2102, 44.78976]"
    );
}

/// Option (c): the forecast low is the user-supplied recent severe low, verbatim; with the
/// input absent the whole §4 chain degrades to unknown — never a guessed number.
#[test]
fn forecast_low_option_c_uses_the_recent_severe_low_and_degrades_without_it() {
    let mut judgment = tutorial_judgment();
    judgment.forecast_low_option = ForecastLowOption::RecentSevereLow;
    judgment.recent_severe_low = Some(d("11.00"));
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    assert_eq!(
        out.risk_reward.forecast_low,
        Some(d("11.00")),
        "option (c) = the user's severe low verbatim"
    );
    assert_eq!(out.risk_reward.present_price_zone, Some(Zone::Buy));

    judgment.recent_severe_low = None;
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    assert_eq!(
        out.risk_reward.forecast_low, None,
        "option (c) without its input is unknown"
    );
    assert_eq!(out.risk_reward.zones, None);
    assert_eq!(out.risk_reward.upside_downside, UpsideDownside::Unknown);
    assert_eq!(
        out.verdict_facts.ud_at_or_above_target,
        CriterionFact::UnmetByInsufficiency
    );
}

// ── Positive flag firings the dev suite only tests negatively ──

/// `eps_lags_sales` fires on a strict lag: flat EPS (CAGR exactly 0%) against 10%/yr sales.
#[test]
fn eps_lags_sales_fires_when_eps_cagr_is_strictly_below_sales_cagr() {
    // Flat EPS 1.00 (ratio 1 ⇒ CAGR exactly 0%); constant PTP 10% and ROE 20% keep every
    // other flag quiet, so the flag vector pins eps_lags_sales alone.
    let financials = canonical(vec![
        full_year(
            2021, "1000", "1.00", "20.00", "10.00", "0.30", "100", "5.00",
        ),
        full_year(
            2022, "1100", "1.00", "20.00", "10.00", "0.30", "110", "5.00",
        ),
        full_year(
            2023, "1210", "1.00", "20.00", "10.00", "0.30", "121", "5.00",
        ),
        full_year(
            2024, "1331", "1.00", "20.00", "10.00", "0.30", "133.1", "5.00",
        ),
        full_year(
            2025, "1464.1", "1.00", "20.00", "10.00", "0.30", "146.41", "5.00",
        ),
    ]);
    let out = compute(&financials, &tutorial_judgment(), &tutorial_observations());
    assert_eq!(
        out.growth.eps_cagr_pct,
        Some(d("0")),
        "1.00 → 1.00 is exactly 0%"
    );
    assert_eq!(
        out.quality_flags,
        vec![QualityFlagKey::EpsLagsSales],
        "0% < 10% is a strict lag; everything else is quiet by construction \
         (PTP even at 10, ROE even at 20, judged P/E 18, U/D 4.96, relative value 75)"
    );
}

/// `roe_low` and `roe_trend_declining` fire together on an ROE marching 25 → 8:
/// average (25+20+16+10+8)/5 = 15.8, latest 8 ⇒ Down (8 − 15.8 < −0.5 pp) and 8 < 10.
#[test]
fn roe_low_and_roe_trend_declining_fire_on_a_collapsing_roe() {
    // bvps = eps × 100 / target-ROE, targets picked so every quotient terminates.
    let financials = canonical(vec![
        full_year(
            2021, "1000", "1.00", "20.00", "10.00", "0.30", "120", "4.00",
        ), // ROE 25
        full_year(
            2022, "1100", "1.10", "22.00", "11.00", "0.33", "121", "5.50",
        ), // ROE 20
        full_year(
            2023, "1210", "1.21", "24.20", "12.10", "0.363", "121", "7.5625",
        ), // ROE 16
        full_year(
            2024, "1331", "1.331", "26.62", "13.31", "0.3993", "119.79", "13.31",
        ), // ROE 10
        full_year(
            2025, "1464.1", "1.4641", "29.282", "14.641", "0.43923", "117.128", "18.30125",
        ), // ROE 8
    ]);
    let out = compute(&financials, &tutorial_judgment(), &tutorial_observations());
    assert_eq!(out.management.avg_roe_pct, Some(d("15.8")), "79 / 5");
    assert_eq!(out.management.latest_roe_pct, Some(d("8")));
    assert_eq!(out.management.roe_trend, Some(Trend::Down));
    assert_eq!(
        out.quality_flags,
        vec![
            QualityFlagKey::PtpTrendDeclining,
            QualityFlagKey::RoeTrendDeclining,
            QualityFlagKey::RoeLow,
        ],
        "flags arrive in pinned-catalog order"
    );
}

/// `ud_below_target` fires on a measured ratio < 3, and a price in the Neutral zone is a
/// MEASURED verdict miss (Unmet), not an insufficiency.
#[test]
fn ud_below_target_fires_and_a_neutral_zone_price_is_a_measured_miss() {
    let mut judgment = tutorial_judgment();
    judgment.current_price = Some(d("30")); // ∈ (23.32992, 34.05984] ⇒ Neutral
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    match out.risk_reward.upside_downside {
        UpsideDownside::Ratio(ud) => assert!(
            ud < d("3"),
            "(44.78976 − 30) / (30 − 12.6) ≈ 0.85 must be below target, got {ud}"
        ),
        ref other => panic!("U/D is measurable at 30, got {other:?}"),
    }
    assert!(
        out.quality_flags.contains(&QualityFlagKey::UdBelowTarget),
        "U/D < 3.0 raises the flag: {:?}",
        out.quality_flags
    );
    assert_eq!(out.risk_reward.present_price_zone, Some(Zone::Neutral));
    let v = &out.verdict_facts;
    assert_eq!(
        v.present_price_in_buy_zone,
        CriterionFact::Unmet,
        "Neutral is a measured miss, not insufficiency"
    );
    assert_eq!(v.ud_at_or_above_target, CriterionFact::Unmet);
    assert_eq!(
        out.returns.projected_appreciation_pct,
        Some(d("49.2992")),
        "14.78976 / 30 × 100"
    );
    assert_eq!(v.appreciation_at_or_above_double, CriterionFact::Unmet);
    assert!(
        !v.quality_value_candidate,
        "a single measured miss breaks the candidate fact"
    );
}

/// The Sell zone classification through the engine: price in the top third.
#[test]
fn a_price_in_the_top_third_classifies_as_sell() {
    let mut judgment = tutorial_judgment();
    judgment.current_price = Some(d("40")); // ∈ (34.05984, 44.78976]
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    assert_eq!(out.risk_reward.present_price_zone, Some(Zone::Sell));
    assert_eq!(out.verdict_facts.present_price_zone, Some(Zone::Sell));
    assert_eq!(
        out.verdict_facts.present_price_in_buy_zone,
        CriterionFact::Unmet
    );
}

// ── out_of_bounds_ratio through the engine (the dev suite covers it only in unit tests) ──

/// A 2023 with EPS 0.10 / high 30 (P/E 300 > 200) and PTP 2420 on sales 1210 (200% > 100)
/// raises `out_of_bounds_ratio` in both computing modules — values still reported, never
/// blocked (spec §3).
#[test]
fn out_of_bounds_ratios_are_flagged_through_the_engine_and_still_reported() {
    let financials = canonical(vec![
        full_year(
            2021, "1000", "1.00", "20.00", "10.00", "0.30", "120", "5.00",
        ),
        full_year(
            2022, "1100", "1.10", "22.00", "11.00", "0.33", "121", "5.50",
        ),
        full_year(
            2023, "1210", "0.10", "30.00", "12.10", "0.363", "2420", "0.40",
        ),
        full_year(
            2024, "1331", "1.331", "26.62", "13.31", "0.3993", "119.79", "6.655",
        ),
        full_year(
            2025, "1464.1", "1.4641", "29.282", "14.641", "0.43923", "117.128", "7.3205",
        ),
    ]);
    let out = compute(&financials, &tutorial_judgment(), &tutorial_observations());
    assert_eq!(
        out.findings,
        vec![
            CalcFinding {
                key: PlausibilityKey::OutOfBoundsRatio,
                year: Some(2023),
                context: "ptp_pct",
            },
            CalcFinding {
                key: PlausibilityKey::OutOfBoundsRatio,
                year: Some(2023),
                context: "high_pe",
            },
        ],
        "documented pass order: management (ptp bound) before valuation (high-P/E bound)"
    );
    let m2023 = out
        .management
        .per_year
        .iter()
        .find(|y| y.year == 2023)
        .expect("2023 present");
    assert_eq!(
        m2023.ptp_pct,
        Some(d("200")),
        "the out-of-bounds value is still reported"
    );
    let v2023 = out
        .valuation
        .per_year
        .iter()
        .find(|y| y.year == 2023)
        .expect("2023 usable");
    assert_eq!(v2023.high_pe, Some(d("300")));
}

// ── Direct-only low EPS and its degradation cascade ──

/// `estimated_low_eps` is NEVER derived (v1 rule): with the direct value absent it stays
/// unknown even though the growth judgment is present, and option (a) degrades the whole
/// §4 low side — while the high side keeps computing.
#[test]
fn absent_low_eps_is_never_derived_and_degrades_the_low_side_only() {
    let mut judgment = tutorial_judgment();
    judgment.estimated_low_eps = None; // projected_eps_growth_pct stays Some(10)
    let out = compute(&tutorial_financials(), &judgment, &tutorial_observations());
    assert_eq!(
        out.growth.estimated_low_eps, None,
        "direct-only: a growth judgment must not derive a low EPS"
    );
    assert_eq!(
        out.risk_reward.forecast_high,
        Some(d("44.78976")),
        "the high side is untouched"
    );
    assert_eq!(out.risk_reward.forecast_low, None, "option (a) needs it");
    assert_eq!(out.risk_reward.zones, None);
    assert_eq!(out.risk_reward.upside_downside, UpsideDownside::Unknown);
    assert_eq!(
        out.verdict_facts.present_price_in_buy_zone,
        CriterionFact::UnmetByInsufficiency
    );
}

// ── The Up trend (only Even and Down are asserted elsewhere) ──

/// A PTP marching 8% → 12% trends Up (latest 12 vs average 10, beyond +0.5 pp) — and an
/// improving margin raises NO flag (only the declining trend is in the catalog).
#[test]
fn a_rising_ptp_trends_up_and_raises_no_flag() {
    let financials = canonical(vec![
        full_year(2021, "1000", "1.00", "20.00", "10.00", "0.30", "80", "5.00"), // 8%
        full_year(2022, "1100", "1.10", "22.00", "11.00", "0.33", "99", "5.50"), // 9%
        full_year(
            2023, "1210", "1.21", "24.20", "12.10", "0.363", "121", "6.05",
        ), // 10%
        full_year(
            2024, "1331", "1.331", "26.62", "13.31", "0.3993", "146.41", "6.655",
        ), // 11%
        full_year(
            2025, "1464.1", "1.4641", "29.282", "14.641", "0.43923", "175.692", "7.3205",
        ), // 12%
    ]);
    let out = compute(&financials, &tutorial_judgment(), &tutorial_observations());
    assert_eq!(
        out.management.avg_ptp_pct,
        Some(d("10")),
        "(8+9+10+11+12)/5"
    );
    assert_eq!(out.management.latest_ptp_pct, Some(d("12")));
    assert_eq!(out.management.ptp_trend, Some(Trend::Up));
    assert_eq!(
        out.quality_flags,
        vec![],
        "an improving margin is not a quality defect"
    );
}
